# Generated by Django 5.2.1 on 2026-03-30 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0001_initial'),
        ('students', '0003_studentsupporttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='student',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='refund_expenses', to='students.student'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('teacher_salary', 'Teacher Salary'), ('student_refund', 'Student Refund'), ('other', 'Other')], max_length=20),
        ),
    ]
