# Generated by Django 5.2.1 on 2026-03-30 19:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('expenses', '0002_expense_student_alter_expense_category'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='support_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'support_teacher'}, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='support_salary_expenses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='expense',
            name='category',
            field=models.CharField(choices=[('teacher_salary', 'Teacher Salary'), ('support_salary', 'Support Salary'), ('student_refund', 'Student Refund'), ('other', 'Other')], max_length=20),
        ),
    ]
