# Generated by Django 5.2.1 on 2026-03-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='free_lessons_remaining',
            field=models.IntegerField(default=3),
        ),
    ]
