# Generated by Django 5.2.1 on 2026-03-30 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('students', '0003_studentsupporttask'),
    ]

    operations = [
        migrations.AddField(
            model_name='student',
            name='freeze_refund_done',
            field=models.BooleanField(default=False),
        ),
    ]
