# Generated by Codex on 2026-04-06

from django.db import migrations, models


def set_existing_students_free_lessons_total(apps, schema_editor):
    Student = apps.get_model("students", "Student")
    Student.objects.filter(free_lessons_total=0).update(free_lessons_total=3)


class Migration(migrations.Migration):

    dependencies = [
        ("students", "0004_student_freeze_refund_done"),
    ]

    operations = [
        migrations.AddField(
            model_name="student",
            name="free_lessons_total",
            field=models.IntegerField(default=3),
        ),
        migrations.RunPython(
            set_existing_students_free_lessons_total,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name="student",
            name="free_lessons_total",
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="student",
            name="free_lessons_remaining",
            field=models.IntegerField(default=0),
        ),
    ]
