# Generated by Django 5.2.1 on 2026-03-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='course',
            old_name='price',
            new_name='daily_price',
        ),
        migrations.AlterField(
            model_name='course',
            name='daily_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
        migrations.AddField(
            model_name='course',
            name='monthly_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=12),
        ),
    ]
