# Generated by Django 5.2.1 on 2026-03-30 08:56

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('groups', '0002_group_support_teacher'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='group',
            name='support_teacher',
            field=models.ForeignKey(blank=True, limit_choices_to={'role': 'support_teacher'}, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='support_groups', to=settings.AUTH_USER_MODEL),
        ),
    ]
