# Generated by Django 5.2.1 on 2026-03-30 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='share_percent',
            field=models.DecimalField(decimal_places=2, default=30, max_digits=5),
        ),
    ]
