# Generated by Django 5.2.1 on 2026-03-30 08:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_user_share_percent'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='role',
            field=models.CharField(choices=[('admin', 'Admin'), ('receptionist', 'Receptionist'), ('teacher', 'Teacher'), ('support_teacher', 'Support Teacher')], max_length=20),
        ),
    ]
