# Generated by Django 5.2.1 on 2026-03-30 07:46

import re
import django.core.validators
import django.db.models.deletion
from django.db import migrations, models


PHONE_REGEX = re.compile(r"^(\+998\d{9}|998\d{9}|0\d{9})$")


def normalize_duplicate_lead_phones(apps, schema_editor):
    Lead = apps.get_model("leads", "Lead")
    used_phones = set()

    for lead in Lead.objects.all().order_by("id"):
        phone = (lead.phone or "").strip()
        needs_replacement = not PHONE_REGEX.match(phone) or phone in used_phones

        if needs_replacement:
            seed = 900000000 + lead.id
            candidate = f"+998{seed:09d}"
            while candidate in used_phones:
                seed += 1
                candidate = f"+998{seed:09d}"
            phone = candidate
            lead.phone = phone
            lead.save(update_fields=["phone"])

        used_phones.add(phone)


class Migration(migrations.Migration):

    dependencies = [
        ('courses', '0002_remove_course_price_course_daily_price_and_more'),
        ('leads', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='interested_course',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='interested_leads', to='courses.course'),
        ),
        migrations.RunPython(normalize_duplicate_lead_phones, migrations.RunPython.noop),
        migrations.AlterField(
            model_name='lead',
            name='phone',
            field=models.CharField(max_length=20, unique=True, validators=[django.core.validators.RegexValidator(message="Telefon raqam noto'g'ri formatda. Namuna: +998901234567", regex='^(\\+998\\d{9}|998\\d{9}|0\\d{9})$')]),
        ),
    ]
