# Generated by Django 5.2.1 on 2026-03-30 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('leads', '0002_lead_interested_course_alter_lead_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='lead',
            name='phone2',
            field=models.CharField(blank=True, default='', max_length=20),
        ),
    ]
